# Generated by Django 3.1.7 on 2021-06-02 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='uuid')),
                ('text', models.TextField(max_length=500, verbose_name='item text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='item created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='item updated')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_todo', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoitem', to='todosapp.project', verbose_name='to-do item')),
            ],
        ),
    ]
